version: '3'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: restful-app-spring
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo-db